services:
  db:
    image: mysql:8.0
    container_name: matching_app_mysql
    restart: always
    environment:
      MYSQL_DATABASE: matching_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306" # <-- CHỈ SỬA SỐ 3307 Ở ĐÂY
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: